// Generated by scripts/build-brand-assets.mjs — don't edit by hand.
// Each splash layer's box as a percentage of the stage (the logo's
// visible bounds), so the layers re-assemble the logo exactly at rest.

export const STAGE_ASPECT = 1123 / 998;

export const LAYERS = {
  "steam": {
    "src": "/brand/splash/steam.webp",
    "left": 75.16,
    "top": 11.42,
    "width": 10.86,
    "height": 16.33
  },
  "lid": {
    "src": "/brand/splash/lid.webp",
    "left": 65.36,
    "top": 26.55,
    "width": 23.42,
    "height": 13.73
  },
  "trails": {
    "src": "/brand/splash/trails.webp",
    "left": 14.51,
    "top": 23.15,
    "width": 19.32,
    "height": 20.24
  },
  "swoosh": {
    "src": "/brand/splash/swoosh.webp",
    "left": 26.54,
    "top": 61.42,
    "width": 32.95,
    "height": 8.62
  },
  "wordmark": {
    "src": "/brand/splash/wordmark.webp",
    "left": 0,
    "top": 71.24,
    "width": 100,
    "height": 24.05
  },
  "tagline": {
    "src": "/brand/splash/tagline.webp",
    "left": 7.66,
    "top": 96.99,
    "width": 81.92,
    "height": 3.01
  },
  "mascot": {
    "src": "/brand/splash/mascot.webp",
    "left": 24.93,
    "top": 0,
    "width": 65.63,
    "height": 68.44
  }
} as const;

export type LayerName = keyof typeof LAYERS;
