// Generated by scripts/build-brand-assets.mjs — don't edit by hand.
// Every splash layer's box in source-logo pixels (1254×1254 art); the
// stage is the logo's visible bounds, the mark is the mascot group that
// BrandLogo shows (public/brand/mark.webp) — the splash lands on it.

export const STAGE = {"x":81,"y":158,"w":1123,"h":998};

export const MARK = {"x":244,"y":158,"w":854,"h":683};

export const LAYERS = {
  "steam": {
    "src": "/brand/splash/steam.webp",
    "x": 925,
    "y": 272,
    "w": 122,
    "h": 163
  },
  "lid": {
    "src": "/brand/splash/lid.webp",
    "x": 815,
    "y": 423,
    "w": 263,
    "h": 137
  },
  "trails": {
    "src": "/brand/splash/trails.webp",
    "x": 244,
    "y": 370,
    "w": 234,
    "h": 231
  },
  "swoosh": {
    "src": "/brand/splash/swoosh.webp",
    "x": 379,
    "y": 771,
    "w": 370,
    "h": 86
  },
  "wordmark": {
    "src": "/brand/splash/wordmark.webp",
    "x": 81,
    "y": 869,
    "w": 1123,
    "h": 240
  },
  "tagline": {
    "src": "/brand/splash/tagline.webp",
    "x": 167,
    "y": 1126,
    "w": 920,
    "h": 30
  },
  "tray": {
    "src": "/brand/splash/tray.webp",
    "x": 772,
    "y": 540,
    "w": 326,
    "h": 120
  },
  "legs": {
    "src": "/brand/splash/legs.webp",
    "x": 361,
    "y": 616,
    "w": 549,
    "h": 225
  },
  "body": {
    "src": "/brand/splash/body.webp",
    "x": 409,
    "y": 158,
    "w": 441,
    "h": 495
  },
  "backShoe": {
    "src": "/brand/splash/backShoe.webp",
    "x": 361,
    "y": 652,
    "w": 130,
    "h": 127
  },
  "frontShoe": {
    "src": "/brand/splash/frontShoe.webp",
    "x": 786,
    "y": 706,
    "w": 124,
    "h": 135
  }
} as const;

export type LayerName = keyof typeof LAYERS;
